// Task 3 of the AI job-write-up feature (2026-07-18 design doc): renders
// source_payload.gpLink.aiWriteup (generated by Task 2's
// POST /api/ats/job/ai-writeup) on both job listing surfaces — the in-app
// job payload (mapCareerRoleRowToClient) and the public website payload
// (mapCareerRoleRowToPublicJob / buildPublicJobsResponse / sanitizePublicJob).
//
// LEAK CONTRACT UNDER TEST (identity masking is non-negotiable per CLAUDE.md):
// even if a stored aiWriteup somehow still carried the real practice name or
// street address (e.g. a future write path that forgets to scrub), the
// SHAPED payload must never expose it — buildCareerRoleGpLinkMetaFromRow
// re-applies maskIdentity/scrubWriteup at read time (defense-in-depth), and
// the public payload's PUBLIC_JOB_FIELDS allow-list is a second, independent
// backstop that would strip an unmasked field even if the mask itself failed.
//
// Two kinds of tests, per the task brief:
//  (A) Shaping — call the exported pure mapper functions directly via
//      __testUtils (no HTTP needed; mirrors tests/career-phase2-payloads.test.js).
//  (B) Source-level — read pages/job.html and pages/site-job.html as strings
//      and assert they reference the new fields (mirrors
//      tests/practice-status-page.test.js).
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const RUN_ID = crypto.randomBytes(4).toString('hex');
const DB_FILE = path.join('/tmp', `gplink-job-writeup-render-${RUN_ID}.json`);

let tu;

const NOW = new Date().toISOString();
const PRACTICE_NAME = 'Riverside Medical Centre';
const STREET = '42 River Street';
const ADDRESS = STREET + ', Sunnybank QLD 4109';

const AI_ABOUT_RAW =
  PRACTICE_NAME + ' at ' + STREET + ' is a well-established, GP-owned practice with a supportive team and a stable patient base.';
const AI_HIGHLIGHTS_RAW = [
  PRACTICE_NAME + ' offers on-site nursing support',
  'DPA-eligible location',
  'Strong earning potential'
];

function baseRow(overrides = {}) {
  return {
    id: 'role-writeup-base',
    provider: 'internal_ats',
    provider_role_id: 'ats_writeup_base',
    title: 'GP — Sunnybank',
    masked_title: 'DPA - Sunnybank - Bulk Billing',
    practice_name: PRACTICE_NAME,
    address: ADDRESS,
    location_city: 'Brisbane', location_state: 'QLD', location_country: 'Australia',
    suburb: 'Sunnybank', nearest_city: 'Brisbane',
    billing_model: 'bulk', dpa: true,
    is_active: true, approval_status: 'approved', job_status: 'open', ats_created: true,
    // Deliberately NAME-FREE: internal_ats rows trust the admin-written
    // `summary` verbatim on the public payload (existing, unrelated
    // behavior — see mapCareerRoleRowToPublicJob's comment on `summary`).
    // Keeping this field clean isolates the assertions below to the new
    // aiAbout/aiHighlights masking this task adds, not that pre-existing
    // trust boundary.
    summary: 'Join our friendly team in a supportive practice.',
    updated_at: NOW,
    source_payload: {},
    ...overrides
  };
}

const ROW_WITH_WRITEUP = baseRow({
  id: 'role-writeup-with',
  provider_role_id: 'ats_writeup_with',
  source_payload: {
    gpLink: {
      aiWriteup: {
        about: AI_ABOUT_RAW,
        highlights: AI_HIGHLIGHTS_RAW,
        sources: ['form'],
        generatedAt: NOW
      }
    }
  }
});

const ROW_WITHOUT_WRITEUP = baseRow({
  id: 'role-writeup-without',
  provider_role_id: 'ats_writeup_without'
  // source_payload stays {} (baseRow default) — no aiWriteup generated yet.
});

beforeAll(async () => {
  process.env.AGENT_SKIP_DOTENV = 'true';
  process.env.NODE_ENV = 'test';
  process.env.AUTH_SECRET = 'job-writeup-render-test-' + RUN_ID;
  process.env.REQUIRE_SUPABASE_DB = 'false';
  process.env.SUPABASE_URL = '';
  process.env.SUPABASE_PUBLISHABLE_KEY = '';
  process.env.SUPABASE_SERVICE_ROLE_KEY = '';
  process.env.ENFORCE_SAME_ORIGIN = 'false';
  process.env.DB_FILE_PATH = DB_FILE;

  // Pure mapper functions only — no HTTP server needs to be listening for
  // these tests (NODE_ENV=test also suppresses server.js's own auto-listen).
  const mod = await import('../server.js');
  tu = mod.__testUtils;
});

afterAll(() => {
  try { fs.unlinkSync(DB_FILE); } catch { /* ignore */ }
});

describe('shaping — in-app job payload (mapCareerRoleRowToClient)', () => {
  it('a row WITH aiWriteup exposes masked aiAbout + aiHighlights', () => {
    const card = tu.mapCareerRoleRowToClient(ROW_WITH_WRITEUP);
    expect(typeof card.aiAbout).toBe('string');
    expect(card.aiAbout.length).toBeGreaterThan(0);
    expect(card.aiAbout).not.toContain('Riverside');
    expect(card.aiAbout).not.toContain(STREET);

    expect(Array.isArray(card.aiHighlights)).toBe(true);
    expect(card.aiHighlights.length).toBe(3);
    card.aiHighlights.forEach((h) => expect(h).not.toContain('Riverside'));
  });

  it('a row WITHOUT aiWriteup falls back to empty aiAbout/aiHighlights', () => {
    const card = tu.mapCareerRoleRowToClient(ROW_WITHOUT_WRITEUP);
    expect(card.aiAbout).toBe('');
    expect(card.aiHighlights).toEqual([]);
    // The existing fallback fields are untouched by this feature.
    expect(card.summary).toBeTruthy();
  });
});

describe('shaping — public website job payload (mapCareerRoleRowToPublicJob / buildPublicJobsResponse)', () => {
  it('a row WITH aiWriteup exposes masked aiAbout + aiHighlights', () => {
    const pub = tu.mapCareerRoleRowToPublicJob(ROW_WITH_WRITEUP);
    expect(typeof pub.aiAbout).toBe('string');
    expect(pub.aiAbout.length).toBeGreaterThan(0);
    expect(pub.aiAbout).not.toContain('Riverside');
    expect(pub.aiAbout).not.toContain(STREET);

    expect(Array.isArray(pub.aiHighlights)).toBe(true);
    expect(pub.aiHighlights.length).toBe(3);
    pub.aiHighlights.forEach((h) => expect(h).not.toContain('Riverside'));
  });

  it('a row WITHOUT aiWriteup falls back to empty aiAbout/aiHighlights', () => {
    const pub = tu.mapCareerRoleRowToPublicJob(ROW_WITHOUT_WRITEUP);
    expect(pub.aiAbout).toBe('');
    expect(pub.aiHighlights).toEqual([]);
  });

  it('exposes AI-sorted perks ([{label,value}]) when present, masked', () => {
    const row = baseRow({
      id: 'role-perks',
      provider_role_id: 'ats_perks',
      source_payload: {
        gpLink: {
          aiWriteup: {
            about: AI_ABOUT_RAW,
            highlights: AI_HIGHLIGHTS_RAW,
            perks: [
              { label: 'Income guarantee', value: '$200/hr for 3 months' },
              { label: 'Relocation to ' + PRACTICE_NAME, value: '$25,000' },
            ],
            sources: ['form'],
            generatedAt: NOW
          }
        }
      }
    });
    const pub = tu.mapCareerRoleRowToPublicJob(row);
    expect(Array.isArray(pub.aiPerks)).toBe(true);
    expect(pub.aiPerks.length).toBe(2);
    expect(pub.aiPerks[0]).toEqual({ label: 'Income guarantee', value: '$200/hr for 3 months' });
    // the practice name is stripped from a perk label too
    expect(JSON.stringify(pub.aiPerks)).not.toContain('Riverside');
  });

  it('a row WITHOUT perks exposes an empty aiPerks array', () => {
    expect(tu.mapCareerRoleRowToPublicJob(ROW_WITHOUT_WRITEUP).aiPerks).toEqual([]);
  });

  it('REGRESSION: a STALE stored aiAbout:"" does not clobber the live write-up', () => {
    // The exact prod bug on Erina's listing: updateCareerRoleRow persists the
    // whole meta into source_payload.gpLink, so a job saved in the editor
    // BEFORE its write-up existed carries aiAbout:'' / aiHighlights:[] there.
    // getCareerRoleGpLinkMeta's ...stored spread would blank the freshly
    // derived write-up unless aiAbout/aiHighlights are forced from `derived`.
    const staleRow = baseRow({
      id: 'role-writeup-stale',
      provider_role_id: 'ats_writeup_stale',
      source_payload: {
        gpLink: {
          aiAbout: '',            // stale, persisted before the write-up
          aiHighlights: [],       // stale
          aiWriteup: {
            about: AI_ABOUT_RAW,  // the real, current write-up
            highlights: AI_HIGHLIGHTS_RAW,
            sources: ['form'],
            generatedAt: NOW
          }
        }
      }
    });
    const pub = tu.mapCareerRoleRowToPublicJob(staleRow);
    expect(pub.aiAbout.length).toBeGreaterThan(0);
    expect(pub.aiHighlights.length).toBe(3);
  });

  it('DEFENSE-IN-DEPTH: a public aiAbout containing the practice name/address gets stripped through the full sanitize pipeline', () => {
    // buildPublicJobsResponse is the exact function GET /api/public/jobs
    // calls: mapCareerRoleRowToPublicJob -> sanitizePublicJob for every row.
    const resp = tu.buildPublicJobsResponse([ROW_WITH_WRITEUP], new URLSearchParams());
    expect(resp.jobs.length).toBe(1);
    const job = resp.jobs[0];
    expect(job.aiAbout).not.toContain('Riverside');
    expect(job.aiAbout).not.toContain(STREET);
    expect(JSON.stringify(job.aiHighlights)).not.toContain('Riverside');
    // Whole-object leak check — no field on the public job carries the
    // practice name, address, or a website URL.
    const serialized = JSON.stringify(job);
    expect(serialized).not.toContain('Riverside');
    expect(serialized).not.toContain(STREET);
  });

  it('DEFENSE-IN-DEPTH: sanitizePublicJob (PUBLIC_JOB_FIELDS allow-list) strips any non-whitelisted identity field even if a mapper accidentally attached one', () => {
    // Simulates a hypothetical future bug where a mapper attaches raw
    // identity fields alongside an already-masked aiAbout/aiHighlights — the
    // allow-list must still keep the public shape clean, independent of the
    // maskIdentity backstop tested above.
    const fakeMapped = {
      id: 'x',
      title: 'GP role',
      aiAbout: 'A masked description with no identity in it.',
      aiHighlights: ['A masked highlight.'],
      practiceName: PRACTICE_NAME,
      address: ADDRESS,
      websiteUrl: 'https://riverside-medical.example.test'
    };
    const sanitized = tu.sanitizePublicJob(fakeMapped);
    expect(sanitized.aiAbout).toBe('A masked description with no identity in it.');
    expect(sanitized.aiHighlights).toEqual(['A masked highlight.']);
    expect(sanitized.practiceName).toBeUndefined();
    expect(sanitized.address).toBeUndefined();
    expect(sanitized.websiteUrl).toBeUndefined();
    expect(JSON.stringify(sanitized)).not.toContain('Riverside');
  });
});

describe('source — pages reference the AI write-up fields', () => {
  const jobHtml = fs.readFileSync(path.join(ROOT, 'pages/job.html'), 'utf8');
  const siteJobHtml = fs.readFileSync(path.join(ROOT, 'pages/site-job.html'), 'utf8');

  it('job.html references role.aiAbout (About block prefers the AI write-up)', () => {
    expect(jobHtml).toContain('aiAbout');
  });

  it('job.html references role.aiHighlights (buildBenefitsHtml prefers the AI highlights)', () => {
    expect(jobHtml).toContain('aiHighlights');
  });

  it('site-job.html references job.aiAbout (About section prefers the AI write-up)', () => {
    expect(siteJobHtml).toContain('aiAbout');
  });

  it('both pages render aiPerks (AI-sorted commercial terms replace the raw dump)', () => {
    expect(jobHtml).toContain('aiPerks');
    expect(siteJobHtml).toContain('aiPerks');
  });
});
