#!/usr/bin/env node
/*
 * Seed the local-JSON dev database (data/app-db.json) with realistic ATS data,
 * ported from the approved prototype (pages/ceo-dashboard-prototype.html), so the
 * real ceo-dashboard.html, running locally against the real /api/ats & /api/ceo
 * endpoints + the real lib/ats-intent calculator, looks and behaves like the
 * approved prototype. Prod/preview reads the equivalent Supabase tables instead.
 *
 *   node scripts/seed-ats-dev.js
 *
 * Re-runnable: it replaces only the ats* collections, leaving other dev data intact.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const DB_FILE = process.env.DB_FILE_PATH || path.join(__dirname, '..', 'data', 'app-db.json');

// rail keys: myintealth, amc, career (Secure Placement), ahpra, pbs, commencement
const RAIL = { 'Commencement': 'commencement', 'PBS & Medicare': 'pbs', 'AHPRA': 'ahpra', 'AMC': 'amc', 'MyIntealth': 'myintealth', 'Placement': 'career' };

const practices = [
  { id: 'p1', name: 'Greenslopes Family Medical', location_city: 'Brisbane', location_state: 'QLD', practice_type: 'GP Clinic, Mixed billing', contact_name: 'Dr. Helen Carter', contact_email: 'admin@greenslopesfm.com.au', contact_phone: '07 3845 1100', ahpra_number: 'PRA-QLD-44821', source: 'backfill', is_active: true },
  { id: 'p2', name: 'Riverina Rural Practice', location_city: 'Wagga Wagga', location_state: 'NSW', practice_type: 'Rural · DPA · Visa-friendly', contact_name: 'Practice Mgr · Joanne Pike', contact_email: 'jobs@riverinarural.com.au', contact_phone: '02 6921 4400', ahpra_number: 'PRA-NSW-21097', source: 'backfill', is_active: true },
  { id: 'p3', name: 'Sunshine Coast Health', location_city: 'Maroochydore', location_state: 'QLD', practice_type: 'Multi-site · Mixed billing', contact_name: 'Dr. Aaron Boyd', contact_email: 'careers@sunshinecoasthealth.au', contact_phone: '07 5443 8800', ahpra_number: 'PRA-QLD-30562', source: 'backfill', is_active: true },
  { id: 'p4', name: 'Perth Metro GP', location_city: 'Perth', location_state: 'WA', practice_type: 'GP Clinic, Private billing', contact_name: 'Dr. Nina Sandhu', contact_email: 'hello@perthmetrogp.com.au', contact_phone: '08 9322 7600', ahpra_number: 'PRA-WA-11843', source: 'backfill', is_active: true },
  { id: 'p5', name: 'Tasman Medical Centre', location_city: 'Hobart', location_state: 'TAS', practice_type: 'GP Clinic, Mixed billing', contact_name: 'Practice Mgr · Greg Hall', contact_email: 'admin@tasmanmedical.au', contact_phone: '03 6234 5500', ahpra_number: 'PRA-TAS-09210', source: 'backfill', is_active: true }
];

const jobs = [
  { id: 'j1', title: 'General Practitioner, VR', practice_id: 'p1', practice_name: 'Greenslopes Family Medical', location_city: 'Brisbane', location_state: 'QLD', employment_type: 'Permanent · Full-time', billing_model: 'Mixed billing', is_active: true, job_status: 'open', ats_created: true, provider: 'internal_ats', published_at: '2026-06-10' },
  { id: 'j2', title: 'GP, Non-VR (DPA, visa support)', practice_id: 'p2', practice_name: 'Riverina Rural Practice', location_city: 'Wagga Wagga', location_state: 'NSW', employment_type: 'Permanent · Full-time', billing_model: 'Mixed billing', is_active: true, job_status: 'open', ats_created: true, provider: 'internal_ats', published_at: '2026-06-14' },
  { id: 'j3', title: 'GP Registrar', practice_id: 'p3', practice_name: 'Sunshine Coast Health', location_city: 'Maroochydore', location_state: 'QLD', employment_type: 'Permanent · Part-time', billing_model: 'Mixed billing', is_active: true, job_status: 'open', ats_created: true, provider: 'internal_ats', published_at: '2026-06-19' },
  { id: 'j4', title: 'General Practitioner, Private', practice_id: 'p4', practice_name: 'Perth Metro GP', location_city: 'Perth', location_state: 'WA', employment_type: 'Permanent · Full-time', billing_model: 'Private billing', is_active: true, job_status: 'open', ats_created: true, provider: 'internal_ats', published_at: '2026-06-21' },
  { id: 'j5', title: 'GP, Mixed billing', practice_id: 'p5', practice_name: 'Tasman Medical Centre', location_city: 'Hobart', location_state: 'TAS', employment_type: 'Permanent · Full-time', billing_model: 'Mixed billing', is_active: true, job_status: 'filled', ats_created: true, provider: 'internal_ats', published_at: '2026-05-02' }
];

// Board applications, id, job, candidate name/country/email, stage, notes
const board = [
  { id: 'c1', name: 'Dr Aisha Khan', country: 'United Kingdom', career_role_id: 'j1', ats_stage: 'applied', email: 'aisha.khan@nhs.uk', ats_notes: '' },
  { id: 'c2', name: 'Dr Liam O’Connor', country: 'Ireland', career_role_id: 'j1', ats_stage: 'submitted', email: 'l.oconnor@hse.ie', ats_notes: 'Strong rural experience.' },
  { id: 'c3', name: 'Dr Priya Nair', country: 'United Kingdom', career_role_id: 'j1', ats_stage: 'reviewing', email: 'priya.nair@nhs.uk', ats_notes: 'Practice reviewing CV this week.' },
  { id: 'c4', name: 'Dr Marcus Webb', country: 'New Zealand', career_role_id: 'j1', ats_stage: 'interview', email: 'm.webb@health.nz', ats_notes: 'Interview booked Fri 2pm AEST.' },
  { id: 'c5', name: 'Dr Sofia Ramos', country: 'Ireland', career_role_id: 'j1', ats_stage: 'offer', email: 'sofia.ramos@hse.ie', ats_notes: 'Verbal offer extended.' },
  { id: 'c6', name: 'Dr Tao Chen', country: 'United Kingdom', career_role_id: 'j2', ats_stage: 'applied', email: 'tao.chen@nhs.uk', ats_notes: '' },
  { id: 'c7', name: 'Dr Hannah Schmidt', country: 'United Kingdom', career_role_id: 'j2', ats_stage: 'submitted', email: 'h.schmidt@nhs.uk', ats_notes: '' },
  { id: 'c8', name: 'Dr Daniel Okoro', country: 'Ireland', career_role_id: 'j2', ats_stage: 'interview', email: 'd.okoro@hse.ie', ats_notes: 'Keen on regional + DPA.' },
  { id: 'c9', name: 'Dr Yuki Tanaka', country: 'United Kingdom', career_role_id: 'j2', ats_stage: 'hired', email: 'yuki.tanaka@nhs.uk', ats_notes: 'Contract signed, commencing Aug.' },
  { id: 'c10', name: 'Dr Emma Wilson', country: 'New Zealand', career_role_id: 'j3', ats_stage: 'applied', email: 'e.wilson@health.nz', ats_notes: '' },
  { id: 'c11', name: 'Dr Raj Patel', country: 'United Kingdom', career_role_id: 'j3', ats_stage: 'reviewing', email: 'raj.patel@nhs.uk', ats_notes: '' },
  { id: 'c12', name: 'Dr Nadia Hassan', country: 'United Kingdom', career_role_id: 'j3', ats_stage: 'not_proceeding', email: 'n.hassan@nhs.uk', ats_notes: 'Practice passed, location mismatch.' },
  { id: 'c13', name: 'Dr James Murphy', country: 'Ireland', career_role_id: 'j4', ats_stage: 'submitted', email: 'j.murphy@hse.ie', ats_notes: '' },
  { id: 'c14', name: 'Dr Lucia Ferraro', country: 'United Kingdom', career_role_id: 'j4', ats_stage: 'offer', email: 'l.ferraro@nhs.uk', ats_notes: 'Awaiting offer acceptance.' }
];

const COMMS = {
  g1: { messages30d: 38, avgReplyHrs: 1.5, tone: 'Enthusiastic', engagementVal: 0.95, aiRead: 'Highly responsive across WhatsApp and email, usually replies within the hour. Consistently positive, proactive, asks forward-looking questions. Strong buying signals.' },
  g2: { messages30d: 29, avgReplyHrs: 2, tone: 'Enthusiastic', engagementVal: 0.90, aiRead: 'Very engaged, warm tone, often initiates contact. Keen to lock in start details, clear momentum.' },
  g3: { messages30d: 22, avgReplyHrs: 3, tone: 'Positive', engagementVal: 0.80, aiRead: 'Reliable responder, upbeat and organised. Occasionally needs a nudge but always follows through.' },
  g4: { messages30d: 18, avgReplyHrs: 5, tone: 'Positive', engagementVal: 0.72, aiRead: 'Engaged but practical, questions centre on family and logistics. Tone steady and committed.' },
  g5: { messages30d: 20, avgReplyHrs: 4, tone: 'Positive', engagementVal: 0.75, aiRead: 'Good engagement, enthusiastic about the regional move. Quick on WhatsApp.' },
  g6: { messages30d: 12, avgReplyHrs: 12, tone: 'Neutral', engagementVal: 0.55, aiRead: 'Moderate engagement, replies but rarely initiates. Tone polite yet non-committal; needs prompting on next steps.' },
  g7: { messages30d: 16, avgReplyHrs: 6, tone: 'Positive', engagementVal: 0.68, aiRead: 'Steady responder, positive about the Sunshine Coast. Engagement solid, not urgent.' },
  g8: { messages30d: 6, avgReplyHrs: 30, tone: 'Hesitant', engagementVal: 0.35, aiRead: 'Slow to reply, short messages. Tone hesitant about timeline, intent unclear, confirm seriousness.' },
  g9: { messages30d: 3, avgReplyHrs: 72, tone: 'Quiet', engagementVal: 0.18, aiRead: 'Largely unresponsive the last 3 weeks. Minimal messages, flat tone, cooling off.' },
  g10: { messages30d: 2, avgReplyHrs: 96, tone: 'Quiet', engagementVal: 0.12, aiRead: 'Almost no two-way contact yet. Has not replied to recent outreach, unqualified.' },
  g11: { messages30d: 15, avgReplyHrs: 6, tone: 'Positive', engagementVal: 0.60, aiRead: 'Engaged and cooperative despite the ID block, responds quickly when chased and wants it resolved.' },
  g12: { messages30d: 17, avgReplyHrs: 5, tone: 'Positive', engagementVal: 0.70, aiRead: 'Responsive and motivated to clear the English-pathway blocker. Constructive tone.' },
  g13: { messages30d: 11, avgReplyHrs: 8, tone: 'Frustrated but committed', engagementVal: 0.62, aiRead: 'Still responsive but tone shows growing frustration at the PSV delay. Committed, needs reassurance to stay warm.' }
};

// GPs (candidates on file). regStage is a display label; converted to a rail key on seed.
const gpsRaw = [
  { id: 'g1', name: 'Dr Yuki Tanaka', country: 'United Kingdom', email: 'yuki.tanaka@nhs.uk', phone: '+44 7700 900812', reg: 'GMC 7841992', status: 'active', joined: '12 Mar 2026', rso: 'Hazel', zoho: 'ZR-10293', ob: { completed: true, fieldsFilled: 1, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: '18 Aug 2026', city: 'Wagga Wagga, NSW', family: 'Partner + 1 child (age 4)', idVerified: true }, docs: { cv: true, coverLetter: true, primaryDegree: true, idDoc: true }, regStage: 'Commencement', blockedDays: 0, lastActiveDays: 1, calls: [{ when: '24 Jun 2026 · 2:00pm', type: 'Commencement check-in (Zoom)', status: 'completed', summary: 'Confirmed 18 Aug start date with Riverina Rural. Asked about relocation support for partner and childcare near Wagga. Fully documented, contract signed, no blockers. Very engaged and confident.', actions: ['Send relocation + childcare pack', 'Confirm commencement checklist items'] }, { when: '09 Jun 2026 · 11:30am', type: 'Offer discussion (Zoom)', status: 'completed', summary: 'Walked through the offer terms and billing split. Accepted verbally on the call; happy with mixed billing arrangement.', actions: ['Issue contract via Zoho Sign'] }], aiHandover: 'Star candidate, fully documented, contract signed, commencing Aug. No concerns. Keep warm through relocation.' },
  { id: 'g2', name: 'Dr Sofia Ramos', country: 'Ireland', email: 'sofia.ramos@hse.ie', phone: '+353 86 123 4567', reg: 'IMC 408821', status: 'active', joined: '02 Apr 2026', rso: 'Hazel', zoho: 'ZR-10341', ob: { completed: true, fieldsFilled: 1, qualCountry: 'Ireland', specialty: 'MICGP, General Practice', target: '01 Oct 2026', city: 'Brisbane, QLD', family: 'Single', idVerified: true }, docs: { cv: true, coverLetter: true, primaryDegree: true, idDoc: true }, regStage: 'PBS & Medicare', blockedDays: 0, lastActiveDays: 2, calls: [{ when: '21 Jun 2026 · 4:00pm', type: 'Placement update (Zoom)', status: 'completed', summary: 'Greenslopes extended a verbal offer. Sofia keen, asked about Medicare provider number timing and start flexibility. Strong intent, responsive.', actions: ['Chase signed offer from practice', 'Start PBS prescriber application'] }], aiHandover: 'Offer extended at Greenslopes, strong intent. Watch PBS/Medicare timing so start date holds.' },
  { id: 'g3', name: 'Dr Marcus Webb', country: 'New Zealand', email: 'm.webb@health.nz', phone: '+64 21 555 019', reg: 'MCNZ 55831', status: 'active', joined: '19 Mar 2026', rso: 'Hazel', zoho: 'ZR-10277', ob: { completed: true, fieldsFilled: 1, qualCountry: 'New Zealand', specialty: 'FRNZCGP, General Practice', target: '15 Sep 2026', city: 'Brisbane, QLD', family: 'Partner', idVerified: true }, docs: { cv: true, coverLetter: false, primaryDegree: true, idDoc: true }, regStage: 'AHPRA', blockedDays: 0, lastActiveDays: 3, calls: [{ when: '27 Jun 2026 · 10:00am', type: 'Interview prep (Zoom)', status: 'upcoming', summary: '', actions: [] }, { when: '18 Jun 2026 · 9:30am', type: 'AHPRA progress (Zoom)', status: 'completed', summary: 'Reviewed AHPRA application progress. Awaiting supervised practice plan. Marcus organised and proactive; interview with Greenslopes booked for Fri.', actions: ['Prep interview talking points', 'Follow up SPPA-00 with practice'] }], aiHandover: 'Interviewing at Greenslopes, AHPRA in progress. Missing cover letter, request before interview.' },
  { id: 'g4', name: 'Dr Priya Nair', country: 'United Kingdom', email: 'priya.nair@nhs.uk', phone: '+44 7700 900145', reg: 'GMC 7720461', status: 'active', joined: '28 Mar 2026', rso: 'Hazel', zoho: 'ZR-10310', ob: { completed: true, fieldsFilled: 1, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: '01 Nov 2026', city: 'Brisbane, QLD', family: 'Partner + 2 children (ages 6, 9)', idVerified: true }, docs: { cv: true, coverLetter: true, primaryDegree: true, idDoc: false }, regStage: 'AHPRA', blockedDays: 0, lastActiveDays: 5, calls: [{ when: '17 Jun 2026 · 1:00pm', type: 'Onboarding call (Zoom)', status: 'completed', summary: 'Discussed family relocation logistics and school enrolment for two children. CV submitted to Greenslopes; practice now reviewing. English test (IELTS) planned for July.', actions: ['Book IELTS reminder for July', 'Send school catchment info for Brisbane'] }], aiHandover: 'CV under review at Greenslopes. English test only planned, nudge to book to avoid AHPRA delay.' },
  { id: 'g5', name: 'Dr Daniel Okoro', country: 'Ireland', email: 'd.okoro@hse.ie', phone: '+353 87 998 2210', reg: 'IMC 415902', status: 'active', joined: '05 Apr 2026', rso: 'Hazel', zoho: 'ZR-10355', ob: { completed: true, fieldsFilled: 1, qualCountry: 'Ireland', specialty: 'MICGP, General Practice', target: '20 Sep 2026', city: 'Wagga Wagga, NSW', family: 'Single', idVerified: true }, docs: { cv: true, coverLetter: true, primaryDegree: true, idDoc: true }, regStage: 'AMC', blockedDays: 0, lastActiveDays: 4, calls: [{ when: '20 Jun 2026 · 3:30pm', type: 'Regional placement (Zoom)', status: 'completed', summary: 'Very keen on regional + DPA. Interview with Riverina Rural arranged. Comfortable with rural lifestyle, asked about visa support, all aligned.', actions: ['Confirm interview slot', 'Share DPA + visa pathway summary'] }, { when: '12 Jun 2026 · 12:00pm', type: 'Intro call (Zoom)', status: 'no_show', summary: 'Did not attend, rescheduled at his request after a roster clash.', actions: [] }], aiHandover: 'Interviewing at Riverina Rural, strong regional fit. One earlier no-show (roster clash), otherwise reliable.' },
  { id: 'g6', name: 'Dr Aisha Khan', country: 'United Kingdom', email: 'aisha.khan@nhs.uk', phone: '+44 7700 900233', reg: 'GMC 7689201', status: 'active', joined: '09 Apr 2026', rso: 'Hazel', zoho: 'ZR-10362', ob: { completed: true, fieldsFilled: 1, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: '01 Dec 2026', city: 'Brisbane, QLD', family: 'Partner', idVerified: true }, docs: { cv: true, coverLetter: false, primaryDegree: true, idDoc: true }, regStage: 'MyIntealth', blockedDays: 0, lastActiveDays: 8, calls: [{ when: '16 Jun 2026 · 10:30am', type: 'Welcome call (Zoom)', status: 'completed', summary: 'Early stage, just applied to Greenslopes. Walked through registration journey. Has not started English test or cover letter yet. Engaged but needs prompting on next steps.', actions: ['Request cover letter', 'Explain English pathway options'] }], aiHandover: 'Early stage, applied at Greenslopes. No cover letter, no English test started, needs active nudging.' },
  { id: 'g7', name: 'Dr Raj Patel', country: 'United Kingdom', email: 'raj.patel@nhs.uk', phone: '+44 7700 900471', reg: 'GMC 7755120', status: 'active', joined: '31 Mar 2026', rso: 'Hazel', zoho: 'ZR-10318', ob: { completed: true, fieldsFilled: 1, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: '15 Oct 2026', city: 'Maroochydore, QLD', family: 'Partner + 1 child', idVerified: true }, docs: { cv: true, coverLetter: true, primaryDegree: true, idDoc: true }, regStage: 'AMC', blockedDays: 0, lastActiveDays: 6, calls: [{ when: '19 Jun 2026 · 2:30pm', type: 'Placement review (Zoom)', status: 'completed', summary: 'CV submitted to Sunshine Coast Health; practice reviewing. Keen on the Sunshine Coast for lifestyle. IELTS planned for August.', actions: ['Follow up practice review', 'Reminder: IELTS in August'] }], aiHandover: 'CV under review at Sunshine Coast. Solid docs; English only planned.' },
  { id: 'g8', name: 'Dr Tao Chen', country: 'United Kingdom', email: 'tao.chen@nhs.uk', phone: '+44 7700 900688', reg: 'GMC 7798344', status: 'active', joined: '14 Apr 2026', rso: 'Hazel', zoho: 'ZR-10377', ob: { completed: false, fieldsFilled: 0.6, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: 'Not set', city: 'Wagga Wagga, NSW', family: 'Not provided', idVerified: false }, docs: { cv: false, coverLetter: false, primaryDegree: true, idDoc: false }, regStage: 'AMC', blockedDays: 0, lastActiveDays: 12, calls: [{ when: '15 Jun 2026 · 11:00am', type: 'Intro call (Zoom)', status: 'completed', summary: 'Interested in Riverina Rural but onboarding incomplete and ID not yet verified. Slightly hesitant about timeline. Needs to upload CV and complete profile.', actions: ['Complete onboarding', 'Upload CV + verify ID'] }], aiHandover: 'Applied at Riverina but onboarding incomplete, no CV, ID unverified. Lukewarm, confirm genuine intent.' },
  { id: 'g9', name: 'Dr Hannah Schmidt', country: 'United Kingdom', email: 'h.schmidt@nhs.uk', phone: '+44 7700 900502', reg: 'GMC 7811003', status: 'active', joined: '16 Apr 2026', rso: 'Hazel', zoho: 'ZR-10381', ob: { completed: false, fieldsFilled: 0.5, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: 'Not set', city: 'Wagga Wagga, NSW', family: 'Not provided', idVerified: false }, docs: { cv: true, coverLetter: false, primaryDegree: false, idDoc: false }, regStage: 'MyIntealth', blockedDays: 0, lastActiveDays: 20, calls: [{ when: '10 Jun 2026 · 9:00am', type: 'Intro call (Zoom)', status: 'no_show', summary: 'Did not attend; no response to reschedule yet.', actions: ['Re-attempt contact'] }], aiHandover: 'Submitted to Riverina but onboarding half-done, missed intro call, gone quiet 20 days. Cold, re-engage or park.' },
  { id: 'g10', name: 'Dr Emma Wilson', country: 'New Zealand', email: 'e.wilson@health.nz', phone: '+64 21 778 442', reg: 'MCNZ 56012', status: 'active', joined: '18 Apr 2026', rso: 'Hazel', zoho: 'ZR-10390', ob: { completed: false, fieldsFilled: 0.4, qualCountry: 'New Zealand', specialty: 'FRNZCGP, General Practice', target: 'Not set', city: 'Maroochydore, QLD', family: 'Not provided', idVerified: false }, docs: { cv: false, coverLetter: false, primaryDegree: false, idDoc: false }, regStage: 'Placement', blockedDays: 0, lastActiveDays: 9, calls: [], aiHandover: 'Brand new, applied at Sunshine Coast but no onboarding, no docs, no call yet. Unqualified intent; book intro call.' },
  { id: 'g11', name: 'Dr Grace Lim', country: 'United Kingdom', email: 'grace.lim@nhs.uk', phone: '+44 7700 900917', reg: 'GMC 7702588', status: 'under_review', joined: '22 Mar 2026', rso: 'Hazel', zoho: 'ZR-10301', ob: { completed: true, fieldsFilled: 1, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: '01 Nov 2026', city: 'Perth, WA', family: 'Partner', idVerified: false }, docs: { cv: true, coverLetter: false, primaryDegree: true, idDoc: false }, regStage: 'MyIntealth', blockedDays: 6, lastActiveDays: 6, calls: [{ when: '21 Jun 2026 · 1:30pm', type: 'Document help (Zoom)', status: 'completed', summary: 'ID document was rejected (glare on photo). Walked Grace through re-uploading. Account under review until ID clears. Otherwise engaged.', actions: ['Re-upload clear ID', 'Clear under-review flag once verified'] }], aiHandover: 'BLOCKED at MyIntealth, ID re-upload needed (6 days), account under review. Engaged; unblock to keep momentum.' },
  { id: 'g12', name: 'Dr Owen Park', country: 'United Kingdom', email: 'owen.park@nhs.uk', phone: '+44 7700 900324', reg: 'GMC 7766910', status: 'active', joined: '25 Mar 2026', rso: 'Hazel', zoho: 'ZR-10308', ob: { completed: true, fieldsFilled: 1, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: '01 Dec 2026', city: 'Perth, WA', family: 'Single', idVerified: true }, docs: { cv: true, coverLetter: true, primaryDegree: true, idDoc: true }, regStage: 'AHPRA', blockedDays: 5, lastActiveDays: 4, calls: [{ when: '23 Jun 2026 · 11:00am', type: 'AHPRA guidance (Zoom)', status: 'completed', summary: 'AHPRA application is held up, English pathway not yet selected. Explained options; Owen leaning toward OET. Documents otherwise complete.', actions: ['Select English pathway', 'Book OET if chosen'] }], aiHandover: 'BLOCKED at AHPRA, English pathway unset (5 days). Docs complete, engaged; resolve pathway to progress.' },
  { id: 'g13', name: 'Dr Sana Mehta', country: 'United Kingdom', email: 'sana.mehta@nhs.uk', phone: '+44 7700 900756', reg: 'GMC 7733410', status: 'active', joined: '20 Mar 2026', rso: 'Hazel', zoho: 'ZR-10295', ob: { completed: true, fieldsFilled: 1, qualCountry: 'United Kingdom', specialty: 'MRCGP, General Practice', target: '15 Sep 2026', city: 'Brisbane, QLD', family: 'Partner + 1 child', idVerified: true }, docs: { cv: true, coverLetter: true, primaryDegree: true, idDoc: true }, regStage: 'AHPRA', blockedDays: 14, lastActiveDays: 14, calls: [{ when: '13 Jun 2026 · 10:00am', type: 'AHPRA escalation (Zoom)', status: 'completed', summary: 'AHPRA stuck awaiting PSV (primary source verification) for 14 days, third-party delay, not the candidate. Sana frustrated but committed. Reassured on timeline.', actions: ['Escalate PSV with AHPRA', 'Weekly status update to Sana'] }, { when: '04 Jun 2026 · 4:00pm', type: 'Check-in (Zoom)', status: 'no_show', summary: 'Missed due to UK night shift; rescheduled.', actions: [] }], aiHandover: 'BLOCKED at AHPRA, PSV delay (14 days, third-party). Committed candidate; keep updated weekly so intent doesn’t cool.' }
];

const jobById = (id) => jobs.find((j) => j.id === id);
const practiceById = (id) => practices.find((p) => p.id === id);

const candidates = gpsRaw.map((g) => ({
  id: g.id, user_id: g.id, name: g.name, email: g.email, phone: g.phone, country: g.country, reg: g.reg,
  account_status: g.status, joined: g.joined, rso: g.rso, zoho: g.zoho,
  ob: g.ob, docs: g.docs, regStage: RAIL[g.regStage] || 'myintealth', blockedDays: g.blockedDays,
  lastActiveDays: g.lastActiveDays, calls: g.calls, comms: COMMS[g.id] || null, aiHandover: g.aiHandover,
  apps: board.filter((c) => c.name === g.name).map((c) => {
    const j = jobById(c.career_role_id); const p = j ? practiceById(j.practice_id) : null;
    return { id: c.id, job_id: c.career_role_id, job_title: j ? j.title : '-', practice_name: p ? p.name : '', ats_stage: c.ats_stage };
  })
}));

let state = {};
try { state = JSON.parse(fs.readFileSync(DB_FILE, 'utf8')); } catch (e) { state = {}; }
state.atsPractices = practices;
state.atsJobs = jobs;
state.atsApplications = board;
state.atsCandidates = candidates;
state.atsStageAudit = Array.isArray(state.atsStageAudit) ? state.atsStageAudit : [];

fs.mkdirSync(path.dirname(DB_FILE), { recursive: true });
fs.writeFileSync(DB_FILE, JSON.stringify(state, null, 2));
console.log('[seed-ats-dev] Seeded ' + DB_FILE + ' with ' + practices.length + ' practices, ' + jobs.length + ' jobs, ' + board.length + ' board applications, ' + candidates.length + ' candidates.');
