begin;

insert into storage.buckets (id, name, public)
values ('career-hero-images', 'career-hero-images', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "career_hero_images_public_select" on storage.objects;
create policy "career_hero_images_public_select"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'career-hero-images');

drop policy if exists "career_hero_images_admin_insert" on storage.objects;
create policy "career_hero_images_admin_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'career-hero-images'
  and public.is_admin(auth.uid())
);

drop policy if exists "career_hero_images_admin_update" on storage.objects;
create policy "career_hero_images_admin_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'career-hero-images'
  and public.is_admin(auth.uid())
)
with check (
  bucket_id = 'career-hero-images'
  and public.is_admin(auth.uid())
);

drop policy if exists "career_hero_images_admin_delete" on storage.objects;
create policy "career_hero_images_admin_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'career-hero-images'
  and public.is_admin(auth.uid())
);

create table if not exists public.career_hero_cities (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  city_name text not null,
  state_code text not null,
  country text not null default 'Australia',
  latitude double precision not null,
  longitude double precision not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(city_name, state_code, country)
);

create index if not exists idx_career_hero_cities_active
  on public.career_hero_cities(is_active, state_code, city_name);

drop trigger if exists trg_career_hero_cities_updated_at on public.career_hero_cities;
create trigger trg_career_hero_cities_updated_at
before update on public.career_hero_cities
for each row
execute function public.set_updated_at();

alter table public.career_hero_cities disable row level security;
revoke all on table public.career_hero_cities from anon, authenticated;

create table if not exists public.career_hero_city_images (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.career_hero_cities(id) on delete cascade,
  slot_no integer not null check (slot_no between 1 and 10),
  bucket_id text not null default 'career-hero-images',
  object_path text not null,
  alt_text text not null default '',
  credit text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(city_id, slot_no),
  unique(bucket_id, object_path)
);

create index if not exists idx_career_hero_city_images_city_active
  on public.career_hero_city_images(city_id, is_active, slot_no);

drop trigger if exists trg_career_hero_city_images_updated_at on public.career_hero_city_images;
create trigger trg_career_hero_city_images_updated_at
before update on public.career_hero_city_images
for each row
execute function public.set_updated_at();

alter table public.career_hero_city_images disable row level security;
revoke all on table public.career_hero_city_images from anon, authenticated;

create table if not exists public.career_suburb_geo_cache (
  id bigint generated by default as identity primary key,
  suburb text not null,
  state_code text not null,
  country text not null default 'Australia',
  latitude double precision,
  longitude double precision,
  geocode_source text not null default '',
  geocode_status text not null default 'pending',
  last_error text not null default '',
  geocoded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(suburb, state_code, country)
);

create index if not exists idx_career_suburb_geo_cache_lookup
  on public.career_suburb_geo_cache(state_code, suburb, geocode_status);

drop trigger if exists trg_career_suburb_geo_cache_updated_at on public.career_suburb_geo_cache;
create trigger trg_career_suburb_geo_cache_updated_at
before update on public.career_suburb_geo_cache
for each row
execute function public.set_updated_at();

alter table public.career_suburb_geo_cache disable row level security;
revoke all on table public.career_suburb_geo_cache from anon, authenticated;

insert into public.career_hero_cities (slug, city_name, state_code, country, latitude, longitude)
values
  ('adelaide', 'Adelaide', 'SA', 'Australia', -34.9285, 138.6007),
  ('albury-wodonga', 'Albury-Wodonga', 'NSW', 'Australia', -36.0806, 146.9158),
  ('ballarat', 'Ballarat', 'VIC', 'Australia', -37.5622, 143.8503),
  ('bendigo', 'Bendigo', 'VIC', 'Australia', -36.7570, 144.2794),
  ('brisbane', 'Brisbane', 'QLD', 'Australia', -27.4698, 153.0251),
  ('cairns', 'Cairns', 'QLD', 'Australia', -16.9203, 145.7710),
  ('canberra', 'Canberra', 'ACT', 'Australia', -35.2809, 149.1300),
  ('central-coast', 'Central Coast', 'NSW', 'Australia', -33.4255, 151.3417),
  ('darwin', 'Darwin', 'NT', 'Australia', -12.4634, 130.8456),
  ('geelong', 'Geelong', 'VIC', 'Australia', -38.1499, 144.3617),
  ('gold-coast', 'Gold Coast', 'QLD', 'Australia', -28.0167, 153.4000),
  ('hobart', 'Hobart', 'TAS', 'Australia', -42.8821, 147.3272),
  ('launceston', 'Launceston', 'TAS', 'Australia', -41.4332, 147.1441),
  ('mackay', 'Mackay', 'QLD', 'Australia', -21.1411, 149.1860),
  ('melbourne', 'Melbourne', 'VIC', 'Australia', -37.8136, 144.9631),
  ('newcastle', 'Newcastle', 'NSW', 'Australia', -32.9283, 151.7817),
  ('perth', 'Perth', 'WA', 'Australia', -31.9523, 115.8613),
  ('rockhampton', 'Rockhampton', 'QLD', 'Australia', -23.3781, 150.5100),
  ('sunshine-coast', 'Sunshine Coast', 'QLD', 'Australia', -26.6500, 153.0667),
  ('sydney', 'Sydney', 'NSW', 'Australia', -33.8688, 151.2093),
  ('toowoomba', 'Toowoomba', 'QLD', 'Australia', -27.5598, 151.9507),
  ('townsville', 'Townsville', 'QLD', 'Australia', -19.2589, 146.8169),
  ('wollongong', 'Wollongong', 'NSW', 'Australia', -34.4278, 150.8931)
on conflict (slug) do update
set
  city_name = excluded.city_name,
  state_code = excluded.state_code,
  country = excluded.country,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  is_active = true,
  updated_at = now();

commit;
