begin;

create table if not exists public.integration_connections (
  id bigint generated by default as identity primary key,
  provider text not null unique,
  status text not null default 'disconnected',
  accounts_server text not null default 'https://accounts.zoho.com',
  api_domain text not null default '',
  refresh_token text not null default '',
  scopes text[] not null default '{}'::text[],
  connected_by_user_id text not null default '',
  connected_email text not null default '',
  token_last_refreshed_at timestamptz,
  last_sync_at timestamptz,
  last_sync_status text not null default 'idle',
  last_sync_error text not null default '',
  connected_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_integration_connections_provider
  on public.integration_connections(provider);

drop trigger if exists trg_integration_connections_updated_at on public.integration_connections;
create trigger trg_integration_connections_updated_at
before update on public.integration_connections
for each row
execute function public.set_updated_at();

alter table public.integration_connections disable row level security;
revoke all on table public.integration_connections from anon, authenticated;

create table if not exists public.career_roles (
  id bigint generated by default as identity primary key,
  provider text not null default 'zoho_recruit',
  provider_role_id text not null,
  title text not null default '',
  practice_name text not null default '',
  location_city text not null default '',
  location_state text not null default '',
  location_country text not null default 'Australia',
  location_label text not null default '',
  billing_model text not null default '',
  dpa boolean not null default false,
  mmm text not null default '',
  earnings_text text not null default '',
  summary text not null default '',
  employment_type text not null default '',
  practice_type text not null default '',
  support_summary text not null default '',
  tags text[] not null default '{}'::text[],
  visa_pathway_aligned boolean not null default false,
  family_friendly boolean not null default false,
  private_billing boolean not null default false,
  mixed_billing boolean not null default false,
  metro boolean not null default false,
  regional boolean not null default false,
  is_active boolean not null default true,
  source_payload jsonb not null default '{}'::jsonb,
  published_at timestamptz,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, provider_role_id)
);

create index if not exists idx_career_roles_provider_active
  on public.career_roles(provider, is_active, updated_at desc);

create index if not exists idx_career_roles_location
  on public.career_roles(location_state, location_city);

drop trigger if exists trg_career_roles_updated_at on public.career_roles;
create trigger trg_career_roles_updated_at
before update on public.career_roles
for each row
execute function public.set_updated_at();

alter table public.career_roles disable row level security;
revoke all on table public.career_roles from anon, authenticated;

commit;
